---
title: "Script linked to Figure 4: Pallial and subpallial qNSCs are distinguished by Hopx expression."
subtitle: "Figure 3A, 3C, 3D, 3M"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "chaos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load packages

```{r,warning=FALSE, include=T}
suppressWarnings(suppressMessages({
library(AUCell,quietly=T)
library(devtools,quietly=T)
library(tidyverse,quietly=T)
library(Seurat,quietly=T)
library(gridExtra,quietly=T)
library(gt,quietly=T)
library(glue,quietly=T)
library(scater,quietly=T)
library(tm,quietly=T)
library(gghalves,quietly=T)
library(broman,quietly=T)
library(viridis,quietly=T)
library(Cairo,quietly=T)
library(hrbrthemes,quietly=T)
library(ggplot2,quietly=T)
library(cowplot,quietly=T)
library(ggrepel,quietly=T)
library(plyr,quietly=T)
library(grid,quietly=T)
library(doRNG,quietly=T)
library(doSNOW,quietly=T)
library(mixtools,quietly=T)
library(SummarizedExperiment,quietly=T)
library(DT,quietly=T)
library(plotly,quietly=T)
library(NMF,quietly=T)
library(shiny,quietly=T)
library(rbokeh,quietly=T)
library(dynamicTreeCut,quietly=T)
library(R2HTML,quietly=T)
library(Rtsne,quietly=T)
library(zoo,quietly=T)
library(GSEABase,quietly=T)
library(magrittr, quietly=T)
library(imager, quietly=T)
library(EBImage, quietly=T)
library(STutility, quietly=T)
library(magrittr, quietly=T)
library(dplyr, quietly=T)
library(DT, quietly=T)
library(kableExtra, quietly=T)
library(ggpubr, quietly = T)
}))
```

```{r, warning=FALSE}
P12_dSVZ_Seq=readRDS("P12_dSVZ_Seq/P12_dSVZ_Seq.rds")
```

# A

> Fig4A: UMAP highlighting 3 qNSCs subclusters.

```{r,fig.width=5,fig.height=4,fig.align="center"}
Idents(P12_dSVZ_Seq) = "Full_clusters"

qNSC3 = WhichCells(P12_dSVZ_Seq, idents = "qNSC3")
qNSC1 = WhichCells(P12_dSVZ_Seq, idents = "qNSC2")
qNSC2 = WhichCells(P12_dSVZ_Seq, idents = "qNSC3")
DimPlot(P12_dSVZ_Seq, label = F,label.size = 4, pt.size = 1,repel=T,cols= c("#DEDEDE","#DEDEDE","#6F4D0F","#EDC251","#C59226","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE","#DEDEDE"))+NoLegend()

```

# C

> Fig4C: Dot plot analysis revealing that some TFs/TRs are enriched or exclusive to a specific cluster.

```{r,fig.align="center"}
DefaultAssay(P12_dSVZ_Seq)="RNA"
my_levels <- c("aNSC1","aNSC2","aNSC3","aNSC4","Astrocytes" ,"Endothelial/Mural cells","Ependymal cells","GABAergic lineage","GLUergic lineage","Microglia","Neuroblasts","Oligos","qNSC1","qNSC3","qNSC2", "TAPs/Nascent Neurons")
Idents(P12_dSVZ_Seq) <- factor(P12_dSVZ_Seq@active.ident,levels=my_levels)
suppressWarnings(suppressMessages(DotPlot(P12_dSVZ_Seq, features = c("Gsx2","Six3","Rorb","Eno1","Id4","Id3","Id2","Id1","Hopx","Fezf2","Dmrta2","Zic5","Tfap2c","Emx1"), idents = c("qNSC1","qNSC2","qNSC3"), dot.scale = 10) +scale_colour_viridis(option="viridis")+theme_grey()+RotatedAxis()))
```

# D

> Fig4D: Spatial transcriptomic (Visium) showing the expression of Sox2 and Hopx.

```{r}
SVZ.Visium=readRDS("SVZ.Visium/SVZ.Visium.rds")
Idents(SVZ.Visium)="labels"
SVZ.Visium <- RenameIdents(SVZ.Visium,"svze18"="E17.5","svzp2"="P2","svzp12"="P12","svzp22"="P22")
SVZ.Visium$labels <- Idents(SVZ.Visium)
SVZ.Visium@meta.data[["labels"]]=as.character(SVZ.Visium@meta.data[["labels"]])
suppressMessages(suppressWarnings(SVZ.Visium <- suppressMessages(SVZ.Visium %>% 
  SCTransform(verbose = F) %>%
  RunPCA(verbose=F) %>%
  RunUMAP(reduction = "pca", dims = 1:20,verbose = F))))

```

```{r, fig.width=10, fig.height=3,fig.align="center"}

FeatureOverlay(SVZ.Visium, features = "Sox2",
sampleids = 1:4,
cols = c("light grey", "mistyrose", "darkred"),
pt.size = 3,
add.alpha = TRUE,
ncol = 4, show.sb = FALSE,
pt.alpha = 0.1,label.by = "labels")

FeatureOverlay(SVZ.Visium, features = "Hopx",
sampleids = 1:4,
cols = c("light grey", "mistyrose", "darkred"),
pt.size = 3,
add.alpha = TRUE,
ncol = 4, show.sb = FALSE,
pt.alpha = 0.1,label.by = "labels")

```

# M

> Fig4M: Calculation of an AUCell score using best astrocytic markers defined by Zeisel et al., Cell, 2018.

```{r,warning=FALSE,include=F}
Astro_Zeisel = c("Fam107a",
        "Cbs",
        "Mlc1",
        "Ntsr2",
        "Clu",
        "Ppp1r3g",
        "Gm11627",
        "Mfge8",
        "Cldn10",
        "S1pr1")

data_matrix <- GetAssayData(P12_dSVZ_Seq, assay = "RNA")
data_matrix <- as.matrix(data_matrix)

astroSets10 = Astro_Zeisel
astroSets10 <- GeneSet(astroSets10, setName= "astroSets10")
CellTypes10 <- GeneSetCollection(astroSets10)
ranking <- AUCell_buildRankings(data_matrix)

AUC_10 <- AUCell_calcAUC(CellTypes10, ranking)
rankings10 <- apply(AUC_10@assays@data@listData[["AUC"]], 1, function(x) (x-min(x))/(max(x)-min(x))) 
rankings10 <- as.data.frame(rankings10)
rankings10$class <- as.data.frame(P12_dSVZ_Seq@meta.data$Full_clusters, row.names = Cells(P12_dSVZ_Seq))[row.names(rankings10),]
```

```{r,warning=FALSE,fig.align="center"}

my_comparisons <- list(c("Astrocytes", "qNSC1"), 
                       c("Astrocytes", "qNSC2"), 
                       c("qNSC1", "qNSC2"))

astro_quiescent <- c("Astrocytes" = "#B882FC","qNSC1" = "#75540D" , "qNSC2"="#CB9B20")

suppressMessages(suppressWarnings(rankings10 %>%
  filter(class == "qNSC1" |
          class == "qNSC2" | 
      class == "Astrocytes" ) %>%
  ggplot(aes(x = class, y = astroSets10,fill=class)) +
  geom_violin(trim = F,position = "dodge")+ggtitle("AUCell score astrocytes markers")+stat_compare_means(label="p.signif",comparisons = my_comparisons)+
  ylab("AUCell score")+theme_ipsum()+ scale_x_discrete("class", limits = c("qNSC1", "qNSC2","Astrocytes"),labels=c("qNSC1","qNSC2","Astro"))+
  scale_fill_manual(values=astro_quiescent)+NoLegend()))

```
