---
title: "Script linked to Figure S2: A core set of “generic genes” defines distinct cellular states, related to Fig 1."
subtitle: "Figure S2A, S2B"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "chaos"
---
***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load packages

```{r,warning=FALSE, include=T}
suppressWarnings(suppressMessages({
library(tidyverse,quietly=T)
library(Seurat,quietly=T)
library(patchwork,quietly=T)
library(viridis,quietly=T)
library(scales,quietly=T)
library(treemap,quietly=T)
library(ggplot2,quietly=T)
library(ggpubr,quietly = T)
}))
```

```{r,echo=FALSE}
P12_dSVZ_Seq <- readRDS("P12_dSVZ_Seq/P12_dSVZ_Seq.rds")
```

# A

> Fig S2A: UMAP with simplified identity annotation.

```{r,fig.width=7,fig.height=6}
suppressMessages(DimPlot(P12_dSVZ_Seq, label=T,label.size=5,pt.size = 1,group.by = "Simplified_clusters",cols=c("#CD9825","#5AD5C7","#FF666C","#99A424","#B984FB","#FF64FB","#5AD5C7","#FF649A","#FE57CC")))+NoLegend()
```

# B

>Fig S2B : Feature plot cluster idents.

```{r, fig.height=23, fig.width=9}
genes <- c("Foxj1", "Ak7", "Pifo")
ependymalcells <-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#FF666C"))

genes <- c("Thbs4", "Sdc4", "Lrp4")
qNSCs <-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#CD9825") )

genes <- c("Egfr", "Mcm2", "Ascl1")
Taps <-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#5AD5C7") )

genes <- c("Dcx", "Cd24a", "Nrxn3")
Neuroblasts <-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#6E9AF3") )

genes <- c("Aqp4", "Agt", "Lcat")
astrocytes <-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#B984FB") )

genes <- c("Cldn5", "Flt1", "Pecam1")
endothelialcells <-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#FF64FB") )

genes <- c("Pdgfra", "Bmp4", "Sox10")
Oligodendrocytes<-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#FE57CC") )

genes <- c("Cd53", "Tmem119", "C1qa")
microglia<-FeaturePlot(P12_dSVZ_Seq, features = genes, combine = TRUE, order = FALSE, slot = "data", ncol = 3,cols=c("lightgrey", "#FF649A") ) 

ggarrange(ependymalcells, qNSCs, Taps, Neuroblasts, astrocytes, endothelialcells, Oligodendrocytes, microglia, nrow=8)
```
